print("            )            ")
print("            (            ")
print("       ^    )            ")
print("      / \ ---            ")
print("     /   \| |            ")
print("    /  -  \ |            ")
print("   /  (_)  \|            ")
print("  /         \            ")
print(" /|   -   -  \           ")
print("  |  | | | | |\          ")
print("  |  |_| |_| | \         ")
print("  |  __   __ |           ")
print("  | |  | |  ||     #     ")
print("  | | @| |  ||    ###    ")
print("  | |  | |__||   #####   ")
print("\/\/\/\/\/\/\/\/\/\/\/   ")
